### PR TITLE
Release sass dependency

### PR DESCRIPTION
**Pull request by printercu**
Hi! I've got this error:
```
    bootstrap (= 4.0.0.beta2.1) was resolved to 4.0.0.beta2.1, which depends on
      sass (>= 3.5.2)

    scss_lint was resolved to 0.38.0, which depends on
      sass (~> 3.4.1)
```

It should be ok not to use `~>`, as only `sass@4.x.x` may introduce breaking changes.

### CODE REVIEW

**Comment by printercu** [comment]
Seems like not everything so clear :( I've got error with this configuration:

```
SCSSLint::Linter::BorderZero raised unexpected error linting file app/assets/stylesheets/shared/_tables.scss: 'undefined method `to_sass' for ["none"]:Array
Did you mean?  to_s'
```

**Comment by tagliala** [comment]
@printercu please take a look at #877, https://github.com/brigade/scss-lint/issues/877#issuecomment-339966451 and https://github.com/tagliala/scss-lint/commit/ac247889acec6841c4aef81655d8ecc83a373f4d

**Comment by printercu** [comment]
@tagliala thanks! I've checked your commit, it helped to understand. I've used slightly different approach: I added `#to_sass_value` to Array and sass Node. This way it will work in both 3.4 and 3.5 sass versions.

I think we should better add appraisal to test against different sass versions.

**Comment by tagliala** [comment]
>  it looks more like sass issue

@printercu are you able to provide a spec which fails in Sass only? I'm still having troubles in understand what really happens when visiting the tree

**Comment by printercu** [comment]
I even haven't thought of it before, just saw backtrace full of `/gems/sass-3.5.3/lib/sass/tree/visitors/` and thought that it was sass. Now I see that it happens only after `scss_lint/sass/tree` is required. Everything is much more complicated than it seemed to be :)

I'm not sure if i'll be able to try to fix it soon. Maybe i'll really try to migrate to other libs or use this gem until i face an error. For now, with this patch it seems to work for our small codebase.

**Comment by sds** [comment]
Thanks for taking time to dig into this issue, @printercu and @tagliala. I really appreciate the effort and understand it's frustrating that this doesn't seem to be working as hoped.

Given that the problem seems to be caused when we require `scss_lint/sass/tree`, my guess is that the nasty monkey-patching we're doing is causing issues. I figured this would one day come to bite us.

#750 suggests a potential workaround to this problem, which is to not have `Linter` inherit from `Sass::Tree::Visitors::Base`, but define its own methods for traversal.

As you can see, that issue has been around for a while. I no longer work at @brigade and I don't use `scss-lint` at my current employer, so any work I do on this project is entirely out of free time. I think it's possible for someone to hack a solution to #750 in a day, but there may be unknown challenges with that path. I would suggest someone solve #750 independently of everything here (getting all existing tests passing), and getting that merged. 

Once we stop monkey patching we can proceed to tackle the challenge here. Hopefully the work will pay off and we won't hit this strange issue where we attempt to visit a `String`.

However, as things currently stand I'm not comfortable with merging something that breaks on Twitter Bootstrap's codebase, especially when the reproducible test case is so simple. Open to hearing your thoughts.

**Comment by tagliala** [comment]
@sds thanks for your time and for your detailed explanation

I think I need way more time of one day to implement #750, because I need to understand what's behind SCSS-Lint.

Also, I was experiencing #278 in Rails 5.1's system tests but I didn't have time to investigate. Now I realize that it is caused bt scss-lint's monkey patch to Sass, so I think that #750 is a must-have

```
$ rake scss_lint assets:clobber tmp:clear test:system
scss-lint found no lints
Run options: --seed 29292

# Running:

Puma starting in single mode...
* Version 3.10.0 (ruby 2.4.2-p198), codename: Russell's Teapot
* Min threads: 0, max threads: 1
* Environment: test
* Listening on tcp://0.0.0.0:62911
Use Ctrl-C to stop
2016-10-10 00:00:00 +0200: Rack app error handling request { GET /calendar }
#<ActionView::Template::Error: undefined method `bubbles?' for null:Sass::Script::Tree::Literal>
~/.rvm/gems/ruby-2.4.2/gems/sass-3.4.25/lib/sass/tree/visitors/check_nesting.rb:157:in `trans
```

without scss-lint
```
$ rake scss_lint assets:clobber tmp:clear test:system
scss-lint found no lints
Run options: --seed 29292

# Running:

Puma starting in single mode...
* Version 3.10.0 (ruby 2.4.2-p198), codename: Russell's Teapot
* Min threads: 0, max threads: 1
* Environment: test
* Listening on tcp://0.0.0.0:62911
Use Ctrl-C to stop
2016-10-10 00:00:00 +0200: Rack app error handling request { GET /calendar }
#<ActionView::Template::Error: undefined method `bubbles?' for null:Sass::Script::Tree::Literal>
~/.rvm/gems/ruby-2.4.2/gems/sass-3.4.25/lib/sass/tree/visitors/check_nesting.rb:157:in `trans
```

Of course, by omitting scss_lint or by changing order of tests this issue doesn't occurr

**Comment by sds** [comment]
Closing in favor of #927. Thanks for your help here!
