### ISSUE TITLE
undefined method `this'  on Ruby 2.3.1

### ISSUE THREAD

**Issue by ain** [brigade/scss-lint#823]
__How to reproduce__:

1. Install scss_lint on Ruby 2.3.1 from RVM
2. Create `file.scss`:

 ```scss
    img {
      max-width: 100%;
      vertical-align: middle;
    }
  ```

3. Lint it

         $ scss-lint file.scss

__What happens__: error is thrown

```
/Users/ain/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x3fc5f5888e34 scss_lint-0.49.0> (NoMethodError)
	from /Users/ain/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
	from /Users/ain/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
	from /Users/ain/.rvm/gems/ruby-2.3.1/gems/scss_lint-0.49.0/bin/scss-lint:3:in `<top (required)>'
	from /Users/ain/.rvm/gems/ruby-2.3.1/bin/scss-lint:23:in `load'
	from /Users/ain/.rvm/gems/ruby-2.3.1/bin/scss-lint:23:in `<main>'
	from /Users/ain/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/ain/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

__What should happen__: no such error should be thrown.

__UPDATE__: exact same process works fine on rubies `2.1.5`, `2.2.4` and `2.2.5`.

**Comment by sds** [comment]
Hey @ain,

This problem is due to a bug introduced in RubyGems and is unrelated to SCSS-Lint (you can find this exact issue on other projects, e.g. [HAML-Lint](https://github.com/brigade/haml-lint/issues/151), [Overcommit](https://github.com/brigade/overcommit/issues/320), etc). 

You can find out more at https://github.com/rubygems/rubygems/issues/1420. 

Hope that helps!
